title: Security Advisories
description: "CVE advisories and security research notes."
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: htb

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: false

masthead_title: "Security Advisories"
